### PR TITLE
Fix parsing of parameter handling for functions with multiple parameters

### LINKED ISSUE #320: Parsing Metapath functions with multiple parameters drops parameters
### Describe the bug

When using recent versions of metaschema-java, when using functions with multiple parameters, the parser builds a concrete syntax tree and drops parameters and by index reuses the previous arguments to overwrite the value. This parsing error leads to incorrect results from function calls.

### Who is the bug affecting

Developers using Metaschema-enabled software and Metapath-based constraints for model-based documents with Metapath functions that have more than one parameter.

### How do we replicate this issue

1. Use the metaschema-cli to evaluate the function below or run the following unit test.

```sh
metaschema-cli metapath eval --expression "let $boom := function ($argument1, $argument2) { $argument2 } return $boom('a', 'b')"
```

```java
/*
 * SPDX-FileCopyrightText: none
 * SPDX-License-Identifier: CC0-1.0
 */

package gov.nist.secauto.metaschema.core.metapath.cst;

import static org.junit.jupiter.api.Assertions.assertEquals;

import gov.nist.secauto.metaschema.core.metapath.DynamicContext;
import gov.nist.secauto.metaschema.core.metapath.ExpressionTestBase;
import gov.nist.secauto.metaschema.core.metapath.IMetapathExpression;
import gov.nist.secauto.metaschema.core.metapath.IMetapathExpression.ResultType;
import gov.nist.secauto.metaschema.core.metapath.StaticContext;
import gov.nist.secauto.metaschema.core.qname.IEnhancedQName;

import org.junit.jupiter.api.Test;


class FunctionParameterTest
    extends ExpressionTestBase {

  @Test
  void testMultipleParameters() {
    StaticContext staticContext = StaticContext.builder().build();
    DynamicContext dynamicContext = new DynamicContext(staticContext);
    String metapath = "function ($argument1 as meta:string, $argument2 as meta:string) as meta:string { $argument2 }";
    dynamicContext.bindVariableValue(IEnhancedQName.of("boom"), 
    		IMetapathExpression.compile(metapath, staticContext).evaluate(null, dynamicContext));    
    String result = IMetapathExpression.compile("$boom('a', 'b')", staticContext).evaluateAs(null, ResultType.STRING , dynamicContext);
    assertEquals(result, "b");
    
  }
}
```

### Expected behavior (i.e. solution)

The function successfully evaluates to `b` (an item of type `meta:string`.

### Other comments

_No response_

### PR DESCRIPTION
**Pull request by aj-stein-gsa**
# Committer Notes

Fixes #320.

### All Submissions:

- [x] Have you selected the correct base branch per [Contributing](https://github.com/metaschema-framework/metaschema-java/blob/main/CONTRIBUTING.md) guidance?
- [x] Have you followed the guidelines in our [Contributing](https://github.com/metaschema-framework/metaschema-java/blob/main/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/metaschema-framework/metaschema-java/pulls) for the same update/change?
- [x] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [x] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [x] Have you added an explanation of what your changes do and why you'd like us to include them? Yes, see issue for details
- [x] Have you written new tests for your core changes, as applicable?
- ~Have you included examples of how to use your new feature(s)?~ This is a bug fix, proper usage is addressed in unit tests.
- ~Have you updated all website and readme documentation affected by the changes you made?~ This is a bug fix to the internal implementation of a core processing feature of the parser, and Java docs as written stay the same unless instructed otherwise during PR review.

### CODE REVIEW

File: core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCstVisitorTest.java [hunk 1]
```diff
@@ -317,15 +317,15 @@ static Stream<Arguments> testNamedFunctionRefCall() {
...
-}
+      @NonNull String metapath,
+      @NonNull IItem expectedResult) {
+    StaticContext staticContext = StaticContext.builder().build();
+    DynamicContext dynamicContext = new DynamicContext(staticContext);
+
+    IItem result = IMetapathExpression.compile(metapath, staticContext)
+        .evaluateAs(null, IMetapathExpression.ResultType.ITEM, dynamicContext);
+    assertEquals(expectedResult, result);
+  }
```
Comment (aj-stein-gsa) [inline core/src/test/java/gov/nist/secauto/metaschema/core/metapath/cst/BuildCstVisitorTest.java:328]: Sorry this occurred from running `mvn -PCI install` during the PR prep process locally. I can roll this back and commit elsewhere if you would prefer, @david-waltermire.

**Review by david-waltermire — APPROVED** [review]
